### ISSUE TITLE
Caching the `composer.lock` on prefer-lowest

### ISSUE THREAD

**Issue by alexander-schranz** [ramsey/composer-install#112]
If we test a library against `lowest`  the `composer update --prefer-lowest` will take a lot of time, because its it take a lot of more resources to find out the lowest dependencies then the newest dependencies.

But as I think aslong as the `PHP Version`, `PHP Extensions` and the `composer.json` does not change the result of the dependencies for `--prefer-lowest` would always be the same.

I think we could save a lot of resources when we cache the generated `composer.lock` based on a hash value of `PHP Version`, `PHP Extensions` and the `composer.json` and restore on a rerun with `lowest` dependencies the lowest `composer.lock` and do just a `composer install`.

So the `composer update --prefer-lowest` is only done once when the cache does not exist one of the 3 mentioned based hash values changed.

That on `highest` or without a `dependencies` configuration this should have no effect. They should still do the same and install the newest/latest dependencies or use the commited composer.lock.

**Comment by Seldaek** [comment]
Probably makes sense, although I'd perhaps make this optional.. Because I think for most simple projects the --prefer-lowest check really isn't that CPU intensive, and the caching may introduce unexpected issues.

**Comment by alexander-schranz** [comment]
@Seldaek Thank you for your fast response.

Sounds good for me maybe then a general `cache-composer-lock: "7 days"` or something would make sense if its an own option which is not connected to lowest. But would only recommend todo that only for "lowest" dependencies.

**Comment by ramsey** [comment]
I'm not sure whether this was a problem in `v1` of this action, but `v2` is definitely caching the packages for the `--prefer-lowest` option. Please upgrade using `ramsey/composer-install@v2` or `ramsey/composer-install@2.0.0`. Details are available on the [release announcement](https://github.com/ramsey/composer-install/releases/tag/2.0.0) and the [README](https://github.com/ramsey/composer-install/tree/v2#readme).

Thanks!
