### ISSUE TITLE
Q: When is the cache discarded/replaced ?

### ISSUE THREAD

**Issue by jrfnl** [ramsey/composer-install#164]
I think it would be useful to add some information to the `Readme` about the elements used in the cache key and when the cache is replaced by a new cache.

It would be helpful to have that information available as it is essential for deciding whether or not to switch to this action or continue to do the caching manually for complex workflows.

Related discussion: https://github.com/WordPress/wordpress-develop/pull/1511#discussion_r674130418

**Comment by ramsey** [comment]
This action is a proxy for GitHub's own `actions/cache` action. Right now, I don't have a much insight into when the cache is discarded or how to set an expiration time for it. There's an open issue for this in the upstream repo: https://github.com/actions/cache/issues/2

For now, I've just released `v2` of this action, which includes the ability to ignore the cache or set your own custom cache key. This should help.

Please upgrade to version 2 using `ramsey/composer-install@v2` or `ramsey/composer-install@2.0.0`. Details are available on the [release announcement](https://github.com/ramsey/composer-install/releases/tag/2.0.0) and the [README](https://github.com/ramsey/composer-install/tree/v2#readme).

**Comment by jrfnl** [comment]
Thanks @ramsey ! I'll have a look at this soon.
