### ISSUE TITLE
Customising the cache key

### ISSUE THREAD

**Issue by Jamesking56** [ramsey/composer-install#167]
Please add a way that we can customise the cache key. We are getting issues with Dependabot PRs that when dependabot rebases, this action fails because its using a cache from the previous run. It would be nice if we could use our own cache key.

**Comment by clxmstaab** [comment]
wouldn't it be better to make the default cache-cache work with dependabot, instead of a solution which needs configuration from the action user?

any insights from your side what the issue is caused by and how a possible fix could look like?

**Comment by ramsey** [comment]
Thanks for the feature request!

This is implemented in v2, please upgrade using `ramsey/composer-install@v2` or `ramsey/composer-install@2.0.0`. Details are available on the [release announcement](https://github.com/ramsey/composer-install/releases/tag/2.0.0) and the [README](https://github.com/ramsey/composer-install/tree/v2#readme).

Thanks!

**Comment by alexander-schranz** [comment]
@ramsey Thank you for this!
