### ISSUE TITLE
dependencies=lowest should set --prefer-stable

### ISSUE THREAD

**Issue by nicolas-grekas** [ramsey/composer-install#178]
Hi there :wave: 

`--prefer-lowest` makes much more sense with `--prefer-stable`: testing alpha/beta/rc is not useful usually.

**Comment by ramsey** [comment]
Thanks for the suggestion!

This is implemented in v2, please upgrade using `ramsey/composer-install@v2` or `ramsey/composer-install@2.0.0`. Details are available on the [release announcement](https://github.com/ramsey/composer-install/releases/tag/2.0.0) and the [README](https://github.com/ramsey/composer-install/tree/v2#readme).

Thanks!
