### ISSUE TITLE
Compatibility with Composer 1 broken due to validate command

### ISSUE THREAD

**Issue by jrfnl** [ramsey/composer-install#209]
## Description
Composer 1.x does not support the `--no-check-version` and will throw the below error causing the action to error out:
```
  [Symfony\Component\Console\Exception\RuntimeException]
  The "--no-check-version" option does not exist.

validate [--no-check-all] [--no-check-lock] [--no-check-publish] [-A|--with-dependencies] [--strict] [--] [<file>]
``` 

## Steps to reproduce

1. Using Composer 1.x, try to run a `composer install` via the action and see it fail.
2. Run `composer validate --strict: it will indicate the composer.json is valid

Example code to reproduce the issue: https://github.com/jrfnl/composer-install-action-bug/commit/98a82bd8f8c78fd65d5101fd51711c9b25042123

Action run showing the bug: https://github.com/jrfnl/composer-install-action-bug/runs/4633075161?check_suite_focus=true

## Expected behavior
That the dependencies would be installed without errors when using Composer 1.x.

## Environment details
- version of this package: 2.0.2
- PHP version: not relevant
- OS: not relevant

**Comment by ramsey** [comment]
Fixed in #210
