### ISSUE TITLE
Heads-up: upcoming (helpful) change in setupPHP

### ISSUE THREAD

**Issue by jrfnl** [ramsey/composer-install#212]
This is just a heads-up and for your information. 

### Basic premise:

Composer commands when used in CI, should always use the `--no-interaction` flag, which this action already (correctly) takes care of.

### The heads-up:

After [a recent discussion about this](https://github.com/shivammathur/setup-php/pull/547) in the `setup-php` repo, a change has been made in `setup-php` to set the `COMPOSER_NO_INTERACTION=1` flag (commit https://github.com/shivammathur/setup-php/commit/e7e1eeedca2d7e8395e2bb0859fd86ee5f4c6f5e), which will have the same effect for all composer commands run in a job.

This change is expected to be included in the next release of `setup-php`.

### Impact on this action

I expect that this will/should probably not have any impact on this plugin, as users of this action may not necessarily be using the latest version of `setup-php` or may possibly not even be using `setup-php`.

@ramsey Either way, I figured it may be useful for you to know about this change in advance. Please feel free to close this issue if you agree that this upstream change will not impact this action.

**Comment by ramsey** [comment]
Thanks! I agree this shouldn't affect this action.
