### ISSUE TITLE
Yaml is invalid?

### ISSUE THREAD

**Issue by Jamesking56** [ramsey/composer-install#228]
## Description

Running `ramsey/composer-install@v2` gives a weird error:

```
Error: The template is not valid. ramsey/composer-install/v2/action.yml (Line: 61, Col: 12): An error occurred trying to start process
```

## Steps to reproduce

I'm not sure yet, only just started happening - everything was working fine before

## Expected behavior

It works as it did before?

## Environment details

- version of this package: v2 tag, so latest v2
- PHP version: 7.4
- OS: Ubuntu 20.04 (GitHub Hosted Runner, `ubuntu-latest`)

## Additional context

It was working fine before, we've made no workflow changes.

**Comment by ramsey** [comment]
Please share the relevant YAML lines. Thanks!

**Comment by Jamesking56** [comment]
Erm... they are in your YAML files not mine?

**Comment by ramsey** [comment]
Oops! I missed that part. 😳

I'm not sure what that error is about, but try hard-coding the version with `ramsey/composer-install@2.1.0` and see if that helps.

**Comment by Jamesking56** [comment]
Appears to work as normal now, haven't made any changes on our end but the warning is gone... weird!

**Comment by ramsey** [comment]
Great to hear. Maybe just some momentary blip in GitHub Actions.
