### ISSUE TITLE
Error: The process '/usr/local/bin/composer' failed with exit code 1

### ISSUE THREAD

**Issue by ostrolucky** [ramsey/composer-install#230]
Can you please take a look at https://github.com/doctrine/DoctrineBundle/runs/7385827550?check_suite_focus=true#step:6:28? I have no idea why it's failing. This is a job executed by cronjob and I don't see output that would help finding out why is composer binary exiting with status code 1.

**Comment by ramsey** [comment]
There should be debug information printed out like with the other steps. I assume you followed the instructions for debug logging here? https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

**Comment by ostrolucky** [comment]
No matter what I did (including instrucions above), I didn't get output helping me with the problem. However, looks like issue is solved now

**Comment by ramsey** [comment]
Weird. Maybe a momentary blip? Let me know if it happens again. Thanks!

**Comment by bendavies** [comment]
i got this on v1 on an old repo. upgrade to v2 and the error revealed itself
> The composer.json file at './composer.json' does not validate; run 'composer validate' to check for errors
