### ISSUE TITLE
"Could not authenticate against github.com"

### ISSUE THREAD

**Issue by Jean85** [ramsey/composer-install#241]
## Description
I'm getting intermittent `Could not authenticate against github.com` errors in my CI, and I can't pinpoint the problem.

## Steps to reproduce
See https://github.com/facile-it/paraunit/actions/runs/4105982330/jobs/7083607877
From this PR: https://github.com/facile-it/paraunit/pull/183

## Expected behavior
No issues

## Screenshots or output
https://github.com/facile-it/paraunit/actions/runs/4105982330/jobs/7083607877#step:5:95

## Environment details
It seems to happen for `Tests` CI jobs of that project, which are defined like this: https://github.com/facile-it/paraunit/blob/1c5414f0d9b4c67bafe0e05f40dcf9cf83ec20d1/.github/workflows/tests.yaml#L10

## Additional context
The linked PR is very removed from the main branch (new major in the works). But the CI definition is very close, I just dropped older PHP versions: 

I just rerun on the main branch and it works: https://github.com/facile-it/paraunit/actions/runs/4106204844 (failure on Windows is unrelated)

Is it possible that the failure is due to the usage of some additional repositories? I need them to pull some PRs as a dependency patch: https://github.com/facile-it/paraunit/blob/c6a6dc03c48b682ef7060ca218538e2c689edf44/composer.json#L58-L67

**Comment by ramsey** [comment]
I've run into this issue when running builds for projects that require private packages, but I've never seen it when using only public packages.

Here's how I solved it for the private packages, and maybe this will help in your case?

Add the following environment variable to your GitHub Actions workflow file. This can be outside the `jobs`, in which case it will apply to all jobs, or you can set the env var at any step in your jobs to limit it.

```
env:
   COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.PRIVATE_REPO_ACCESS }}"}}'
```

I called the secret `PRIVATE_REPO_ACCESS`, but you can name it whatever you want. It's a GitHub personal access token that has permission to read repos.

**Comment by Jean85** [comment]
You're right, that fixes it, thank you!

I'll file a PR to improve the README in this regard.
