### ISSUE TITLE
File "./composer.json" cannot be found in the current directory  

### ISSUE THREAD

**Issue by mxr576** [ramsey/composer-install#246]
## Description

I keep seeing the above message in build logs, see details below. 

<details>

Run ramsey/composer-install@2.2.0
Run ${GITHUB_ACTION_PATH}/bin/php_version.sh
Run ${GITHUB_ACTION_PATH}/bin/should_cache.sh ""
Run ${GITHUB_ACTION_PATH}/bin/composer_paths.sh \
  ${GITHUB_ACTION_PATH}/bin/composer_paths.sh \
    "" \
    "....." \
    "/usr/bin/php"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
    CACHE_RESTORE_KEY: Linux-php-8.1.21-composer-locked-......

In ConfigCommand.php line 217:
                                                                   
  File "./composer.json" cannot be found in the current directory  
                                                                   

config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [-j|--json] [-m|--merge] [--append] [--source] [--] [<setting-key> [<setting-value>...]]

</details>

## Environment details
IMO N/A

**Comment by onyxmueller** [comment]
Seeing the same issue.

**Comment by ramsey** [comment]
Fixed in 2.3.0
