### ISSUE TITLE
locked version vs. missing lock file

### ISSUE THREAD

**Issue by szepeviktor** [ramsey/composer-install#249]
## My feature title
Would you merge a PR that adds an argument to fail the job when `dependencies: locked` but the lock file is missing?

## Background/problem
I'd like to see that problem in form of a ❌ 

https://github.com/ramsey/composer-install/blob/c49029afecf85fda829d8c6c7f1b5f7b8bc3f7be/bin/composer_install.sh#L19-L22

**Comment by ramsey** [comment]
Sure thing. As long as it's a configurable argument, I think that's be great.
