### ISSUE TITLE
[support] Create new tagged release

### ISSUE THREAD

**Issue by mxr576** [ramsey/composer-install#257]
I've checked whether the fix from #233 has been included in a tagged release, but it appears it hasn't. The 2.2.0 release is about 1.5 years old, and there are pending changes in the dev branch. Could you please create a new tagged release with those changes? Are there any blockers preventing this from being done? Thanks!

https://github.com/ramsey/composer-install/compare/2.2.0...v2

**Comment by ruudk** [comment]
I'm also waiting for a tagged release that includes https://github.com/ramsey/composer-install/pull/252. 

We cannot use `@v2` because we always pin to versions, not to branches.

@ramsey Could you please tag a release? Or maybe promote someone to handle it for you?

**Comment by ramsey** [comment]
2.3.0 is tagged

**Comment by mxr576** [comment]
Thank you! :beer:

**Comment by ramsey** [comment]
Due to BC issues, I have reverted the actions/cache upgrade in version 2.3.1 and have released 3.0.0, which includes the actions/cache upgrade. Please update your pinned versions to 3.0.0. See discussion on #252, for more info.
