### ISSUE TITLE
don't re-install dependencies after cache restore

### ISSUE THREAD

**Issue by staabm** [ramsey/composer-install#31]
I am doing dependency caching the manual way and just found out about this package.
it seems to be a time saver <3. thanks for this great package.

I did some initial tests and it seems to work like expected. I noticed though, that the composer installation process is still triggered on a cache hit.

I learned today in a [different github action](https://github.com/deployphp/deployer/blob/76a50111190bdbd31d997df7c20167693c46967e/.github/workflows/test.yml#L30), that invoking `composer install` after a successfull restore is unnecessary.

wdyt.. could we save this call and the few seconds this requires when running the action on a cache hit?

**Comment by ramsey** [comment]
This action doesn't cache the `vendor/` directory but, rather, the downloaded packages. `composer install` is still necessary to unpack the cached packages into the project's `vendor/` directory and create the autoloader.

If you'll note here: https://github.com/shivammathur/setup-php#cache-composer-dependencies

> Please do not cache `vendor` directory using `action/cache` as that will have side effects.

This action follows that same advice, since it uses `action/cache` internally.

**Comment by adri** [comment]
Does anyone know what those side-effects are? I'm caching the vendor folder on CircleCI for years without issues. Caching the `vendor` folder would remove ~10 seconds from my build which is now spent unpacking archives although nothing changes.

**Comment by ramsey** [comment]
Perhaps @shivammathur can offer some advice on this?

**Comment by shivammathur** [comment]
Caching vendor is not recommended as per this discussion https://github.com/travis-ci/travis-ci/issues/4579.

My reasons for not recommending caching vendor in GitHub Actions are these.

- Not all projects commit `composer.lock` (mostly libraries). If a project only has `composer.json` and uses its hash in the key, then caching vendor can result in it being stuck on old dependencies.

- If `composer.lock` is committed and it changes, the `restore-keys` still might restore an old cache as those are [fallback keys](https://github.com/actions/cache/blob/main/action.yml#L12). If restore keys input is removed, the whole cache is lost as soon as one dependency is updated. So, while some seconds are saved caching vendor when there is a cache hit, the frequency of cache hits overall will decrease.

So, I prefer caching composer internal directory with both keys and restore keys (as it is done currently), and let composer figure out if it wants to use the restored cache for each dependency. This might take some more seconds to extract archives, but the frequency of cache hit in jobs would be better.
